### ISSUE TITLE
Nginx reverse proxy

### ISSUE THREAD

**Issue by machsix** [gvalkov/tailon#11]
First of all, I would like to appreciate the great work of the author! I want to share my experience of setting nginx reverse proxy for the program. For example, if `tailon` listens at `127.0.0.1:12323`, my goal is to redirect web request to `https://www.example.com/log/` to `127.0.0.1:12323` and also create a systemd service to make the program start automatically.

First, I create the following systemd file: `/etc/systemd/system/tailon.service` and run `systemctl daemon-reload`, `systemctl enable tailon`
```bash
[Unit]
Description=Tailon
After=syslog.target

[Service]
Type=simple
User=root
Group=root
# tailon must run as root in order to read /var/log/messages
ExecStart=/usr/local/bin/tailon -c /data/wwwroot/tailon.toml /var/log/messages /data/wwwlogs/*.log
Restart=always

[Install]
WantedBy=multi-user.target
```

Then I create the configuration file `/data/wwwroot/tailon.toml` like the following
```toml
  title = "Tailon file viewer"
  relative-root = "/"
  listen-addr = ["127.0.0.1:12313"]
  allow-download = false
  allow-commands = ["tail", "grep"]

  [commands]

    [commands.tail]
    action = ["tail", "-n", "$lines", "-F", "$path"]

    [commands.grep]
    stdin = "tail"
    action = ["grep", "--text", "--line-buffered", "--color=never", "-e", "$script"]
    default = ".*"
```

Finally, I configure the nginx files `example.conf`, which is the hardest part
```conf
server {
  listen 80;
  server_name example.com www.example.com;
  location / {
    return   301 https://$server_name$request_uri;
  }
}


server {
  listen 443 ssl http2 proxy_protocol;
  include snippets/letsencrypt.conf;
  include snippets/ssl.conf;
  server_name example.com www.example.com;

  location /log/ {
    sub_filter 'href="/' 'href="/log/';
    sub_filter 'href=\'/' 'href=\'/log/';
    sub_filter 'src="/' 'src="/log/';
    sub_filter 'src=\'/' 'src=\'/log/';
    sub_filter_once off;
    proxy_pass http://127.0.0.1:12313/;
  }

  location /ws/ {
    proxy_pass http://127.0.0.1:12313;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_read_timeout 86400;
  }
```

The most tricky part is the `sub_fiter` part in `/log/` block, since the frontend of `tailon` responses html body with css defined at locations like `/vfs/**` and we need to make it to be `/log/vfs/***`. Moreover, you need to visit `http://www.example.com/log/` (**Note the last slash**) in order to make it work.

I personally suggest using `ngx_http_auth_basic_module` module to encrypt the frontend, and also using `HTTPS`. In addition, you need to recompile `nginx` with `--with-http_sub_module` flag to enable the function of `sub_filter`.

I think the program itself can have the function to define the relative path. But I don't know how hard it is to achieve this. :smile:
