### ISSUE TITLE
File example for config folder

### ISSUE THREAD

**Issue by camjac251** [gvalkov/tailon#8]
Is it possible to include an example of how the config would work with aliases and paths

The readme just shows 
```
File, glob and dir filespecs are similar in principle to their # command-line counterparts.
```
which isn't helpful.
I have tried different combinations of what I think it might be couldn't figure it out.

**Comment by iesl2** [comment]
@gvalkov,

I'm also interested in how may we define files in the config:

For example:
```
# General
title = "Tailon file viewer"
relative-root = "/"
listen-addr = ["0.0.0.0:5000"]
allow-download = true
allow-commands = ["tail", "grep", "sed", "awk"]

# Files
alias=Tailon,group=Tailon,/var/log/tailon*
```

But got the error:
**Error parsing config: (9, 9): keys cannot contain , character**

I also tried some different variants:
```
# Files
file = ["alias=Tailon", "group=Tailon", "/var/log/tailon*"]
```
**panic: interface conversion: interface {} is nil, not *toml.Tree***

```toml
[files]

  [files.tailon]
  alias = "Tailon"
  group = "Tailon"
  files = "/var/log/tailon*"
```
```toml

[files]
  files = ["Tailon", "Tailon", "/var/logs/tailon*"]
```
***No files specified on command-line or in config file**

No any of these variants works.

May you please provide an example how may we specify files in the config file?

Thank you!
